name: Build and deploy JAR app to Azure Web App - aerolinea-backend

on:
  push:
    branches:
      - rama-heydi
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: demo/demo

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/demo/demo/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_99F9DDAB8FA949DD8E80ABFA502532BA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_644418C93F4F446180196593CA362033 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_09656DE665CF4C6FAF32E649196F2ACC }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'aerolinea-backend'
          slot-name: 'Production'
          package: '*.jar'
